[project]
name = "mcp-hooks"
version = "0.0.0"
description = "MCP Server"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["mcp", "llm"]
license = { text = "MIT" }
dependencies = [
    "fastmcp>=2.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
